/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunDisplayList: typeof import('./src/components/RunDisplayList.vue')['default']
    RunSearchList: typeof import('./src/components/RunSearchList.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
  const ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElSegmented: typeof import('element-plus/es')['ElSegmented']
  const ElStatistic: typeof import('element-plus/es')['ElStatistic']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
  const ElTag: typeof import('element-plus/es')['ElTag']
  const ElTimeline: typeof import('element-plus/es')['ElTimeline']
  const ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
  const IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
  const Nav: typeof import('./src/components/Nav.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const RunDisplayList: typeof import('./src/components/RunDisplayList.vue')['default']
  const RunSearchList: typeof import('./src/components/RunSearchList.vue')['default']
  const TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
  const WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
}